config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'notes#index'
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord

acts_as_taggable
acts_as_taggable_on :skills, :interests

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  # before_action :move_to_index,except: :index

  def index
    @notes = Note.all
    if params[:id].present?
      @note = Note.find(params[:id])
    else
      @note = Note.new
    end
  end

  def create
    Note.create(memo_params)
    redirect_to action: :index
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to action: :index
  end

  def update
    @note = Note.find(params[:id])
    @note.update(memo_params)
    redirect_to action: :index
  end

  private
  def memo_params
    params.require(:note).permit(:title,:text,:tag_list)
  end

  def move_to_index
    redirect_to action: :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Memo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :integrity => "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/", :rel => "stylesheet"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "notes/header"
    = yield

app/views/notes/_form.html.haml
= form_with model: @note,local: true,class: :area__input do |f|
  = f.text_field :title, placeholder: "タイトル",class: "title-field"
  %i.fa.fa-hashtag
    = f.text_field :tag, placeholder: "タグ追加",class: "tag-field"
  = f.text_area :text, placeholder: "メモ",class: "memo-field"
  .area__edit
    .area__icon
      = f.button class: "memo-btn" do
        %i.fa.fa-save
      =link_to notes_path,class: "memo-btn" do
        %i.fa.fa-times
    .area__filter

app/views/notes/_header.html.haml
.header
  .navbar
    .title
      %h1 memo
    .ul
      %li

app/views/notes/index.html.haml
.contents
  .content-memo
    .area
      = render :partial => "form"
      %table
        %thead
          %th タイトル
          %th 更新日時
          %th タグ
        - @notes.each do |note|
          %tbody
            %td= note.title
            %td= note.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M")
            %td= note.tag
            %td= link_to "編集",notes_path(id: note.id)
            %td= link_to "削除",note,method: :delete
  .content-calender